spring.application.name=authenticator
# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/authenticator_db
spring.datasource.username=postgres
spring.datasource.password= Aryan_27

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT configuration
//= In a production environment, ensure to use a secure and random secret key, \
  and do not hardcode it in the properties file. Consider using environment variables or a secrets management service.
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=900000

jwt.refresh-expiration=604800000

